### ISSUE TITLE
怎么设置repo 的访问权限 

### ISSUE THREAD

**Issue by manajay** [zce/pages-store#1]
没看到config.env.json 里面有填写 auth 或者 token的地方啊

**Comment by zce** [comment]
URL auth

https://github.com/zce/pages-store#authorization

**Comment by manajay** [comment]
```
{
  "storage": {
    "active": "pages-store",
    "pages-store": {
      "repo": "https://<TOKEN>@github.com/zce/images.git",
      "branch": "master",
      "prefix": "https://img.zce.me",
      "format": "{yyyy}/{mm}/{dd}/{name}-{uuid}-{timestamp}-{random}{ext}"
    }
  }
}
```

you mean this , config repo part ?

**Comment by zce** [comment]
Yes, but it depends on the service.

e.g. 

- GitHub: `https://<TOKEN>@github.com/zce/images.git`
- Coding: `https://<USERNAME>:<TOKEN>@git.coding.net/zce/images.git`

**Comment by zce** [comment]
ping @manajay

**Comment by manajay** [comment]
thanks i will try later

**Comment by manajay** [comment]
How to make a right prefix , i want to custom my prefix .
 But it turns out that the only answer is 
`https://raw.githubusercontent.com/用户名/仓库名分支名称`

**Comment by zce** [comment]
https://help.github.com/articles/using-a-custom-domain-with-github-pages/
